;=================================================
; Name: Daisha Haymon
; Email: dhaym002@ucr.edu
; 
; Lab: lab 3, ex 2
; Lab section: 001
; TA: Ariel
; 
;=================================================

.ORIG x3000

LEA R1, ARRAY        ; LOAD THE BLOCK[0] INTO R1
LEA, R0 PROMPT       ; LOAD THE STARTING ADDRESS OF THE PROMPT STRING INTO R0
PUTS                 ; PRINT THE VALUES IN ADDRESSES STARTING AT R0

ADD R2, R2, #10      ; LOADING COUNTER VALUES INTO R2

DO_WHILE_LOOP
GETC                 ; TRAP VALUE INTO R0
OUT                  ; ECHO ENTERED KEY BACK TO THE USER
STR R0, R1, #0       ; STORE R0 INTO ARRAY[ARRAY+1]
ADD R1, R1 #1        ; INCREASE ADDRESS VALUE IN R1 TO ARRAY[ARRAY+1]
ADD R2, R2, #-1      ; DECREMENT COUNTER VALUE IN R2
BRzp DO_WHILE_LOOP   ; REEPAT TRAP X21 ROUTINE UNTIL ALL ARRAY POSITIONS ARE FILLED
END_DO_WHILE_LOOP    


HALT

PROMPT .STRINGZ "ENTER EXACTLY 10 CHARACTERS: "
ARRAY .BLKW #10

.END