;=================================================
; Name: Daisha Haymon
; Email: dhaym002@ucr.edu
; 
; Lab: lab 3, ex 4
; Lab section: 001
; TA: Ariel
; 
;=================================================

.ORIG x3000

LEA R1, ARRAY        ; LOAD THE BLOCK[0] INTO R1
LEA, R0 PROMPT       ; LOAD THE STARTING ADDRESS OF THE PROMPT STRING INTO R0
PUTS                 ; PRINT THE VALUES IN ADDRESSES STARTING AT R0
ADD R2, R2, #10      ; LOADING COUNTER VALUE INTO R2
LEA R6, ENDOFTRANSMISSION ; THE FIRST DO_WHILE_LOOP WILL STORE VALUES IN THE ARRAY 
DO_WHILE_LOOP
GETC                 ; TRAP VALUE INTO R0
ADD R4, R0 #0        ; PUT R0 INTO R4
; BEFORE YOU STORE THE VALUE INTO THE ARRAY MAKE SURE IT ISN'T ENDLINE
; SUBTRACT END OF TRANSMISSION FROM THE INPUT 
; The only numbers lower than 003 are the start of text, header, and "null"
COMPARISON_LOOP
ADD R4, R4, #-1      ; R4 USER INPUT SUBTRACT FROM
ADD R6, R4, #-1      ; SUBTRACT USERINTPUT VALUE FROM R6
BRp                  ; BRz
                     
BRp COMPARISON_LOOP
END_COMPARISON_LOOP


OUT                  ; ECHO ENTERED KEY BACK TO THE USER
STR R0, R1, #0       ; STORE R0 INTO ARRAY[ARRAY+1]
ADD R1, R1 #1        ; INCREASE ADDRESS VALUE IN R1 TO ARRAY[ARRAY+1]
ADD R2, R2, #-1      ; DECREMENT COUNTER VALUE IN R2


BRp DO_WHILE_LOOP    ; REEPAT TRAP X21 ROUTINE UNTIL ALL ARRAY POSITIONS ARE FILLED
END_DO_WHILE_LOOP    ; 
LEA R1, ARRAY        ; 
ADD R0, R0, #0       ;

LEA R5, SPACE 
LDR R0, R5, #0
OUT

; DO_WHILE_PRINT_LOOP WILL PRINT THE VALUES IN THE ARRY

ADD R4, R4, #10      ; LOADING COUNTER VALUE INTO R4
LEA R1, ARRAY        ; LOAD ARRAY ADDRESS INTO R3
DO_WHILE_LOOP_PRINT
LDR R0, R1, #0
OUT
ADD R1, R1, #1
ADD R4, R4, #-1
BRp DO_WHILE_LOOP_PRINT
END_DO_WHILE_LOOP_PRINT
HALT




PROMPT .STRINGZ "ENTER EXACTLY 10 CHARACTERS: "
ARRAY .BLKW #100
SPACE .FILL x20; 
ENDOFTRANSMISSION .FILL x04

; FILL THIS WITH THE NEWLINE CHARACTER
; FILL A REGISTER WITH THE NEWLINE CHARACTER
; DO I HAVE TO DO A SUBTRACT LOOP EVERYTIME THE USER ENTERS A CHAR?


.END

.ORIGIN 

x4000



ARRAY .BLKW #100


.END

;Consider BRnz